version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    volumes:
      - .:/api
    ports:
      - "8000:3000"
    environment:
      - "DATABASE_URL=postgres://postgres@db/postgres"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    volumes:
      - .:/web
    ports:
      - "3000:3000"
    environment:
      - "API_URL=http://localhost:8000"
      - "NEXTAUTH_SECRET=fc93bc077815e646705c4993eb7642cc"
      - "NEXTAUTH_URL=http://localhost:3000"
    depends_on:
      - api

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: