name: API Lint Workflow

on:
  workflow_run:
    workflows: [Build Workflow]
    types:
      - completed
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: API Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './api/go.mod'
          cache-dependency-path: './api/go.sum'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: 'latest'
          working-directory: './api'
      - run: make lint/sql
        working-directory: './api'
