name: API Workflow

on:
  push:
    branches: [ main ]
    paths: [ './api' ]
  pull_request:
    branches: [ main ]
    paths: [ './api' ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: API Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './api/go.mod'
      - run: make build
        working-directory: './api'

  lint:
    name: API Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './api/go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'latest'
          working-directory: './api'

  test:
    name: API Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './api/go.mod'
      - run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - run: make db/migrations/up
        working-directory: './api'
      - run: make test/cov/report
        working-directory: './api'
      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v3
