name: Build & Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: 'package.json'
      - uses: falti/dotenv-action@v1.0.4
      - run: yarn install
      - run: yarn build
      - run: zip build.zip ./* -r -x "**/node_modules/*"
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip

  static-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: unzip build.zip
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: 'package.json'
      - run: yarn lint

  test:
    needs: [build]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: unzip build.zip
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: 'package.json'
      - run: yarn db:test
      - run: yarn test
