name: Web Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: './web/package.json'
          cache-dependency-path: './web/yarn.lock'
      - run: yarn install
        working-directory: './web'
      - run: yarn build
        working-directory: './web'

  lint:
    name: Web Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: './web/package.json'
          cache-dependency-path: './web/yarn.lock'
      - run: yarn install
        working-directory: './web'
      - run: yarn lint
        working-directory: './web'

  test:
    name: Web Test Workflow
    uses: ./.github/workflows/web-test.yml
